import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import AppProviders from '@/components/core/app-providers';
import AppInitActions from '@/components/core/app-init-actions';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'MyTime',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk" className={geistSans.variable}>
      <body className={`${geistMono.variable} antialiased`}>
        <AppProviders>
          <AppInitActions />
          {children}
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}
